/**
 * Plan Store — Pete Bot v2 Plan service backing store.
 *
 * DB-backed store for the Plan lifecycle introduced in PB.1 (migration 005):
 *   - createPlan          → agents call via proposeAction(); alertmanager posts; users create
 *   - presentPlan         → notification router marks plan presented (Discord/MC bell sent)
 *   - recordClick         → atomic first-click-wins on (plan_id, action_id); rejects duplicates
 *   - dispatchPlan        → user-approved → MC dispatches the proposed fix; links agent_run_id
 *   - transitionStatus    → general state transition (succeeded/failed/stuck/resolved/expired/...)
 *   - getPlan             → fetch by id + its actions + recent events
 *   - listPlans           → filter by status / kind / age
 *   - listExpiredPresented → for Pete Bot expiry sweep (PB.8)
 *   - logEvent            → append to plan_events (called internally on every transition)
 *
 * State machine (enforced in stateMachine.ts):
 *
 *   pending → presented → clicked → dispatched → in_progress → succeeded
 *                                                              → failed   (→ Retry/Resolve)
 *                                                              → stuck    (→ proposal buttons)
 *   presented → dismissed | expired
 *   any → resolved (manual close from MC Web)
 *
 * Design notes:
 *   - Idempotency is enforced at the DB layer: recordClick uses
 *     UPDATE plan_actions ... WHERE acted_at IS NULL — atomic; second
 *     click sees 0 rows affected and is rejected.
 *   - Every public mutation emits a plan_events row in the same
 *     transaction as the table update. No silent state changes.
 *   - Plan IDs are TEXT (e.g. 'pl_a3f9c1'); generated by Plan service,
 *     not by Postgres. Matches the existing TaskQueue ID style.
 */

import db from '../db/client.js';
import { logger } from '../utils/logger.js';
import { isValidTransition, type PlanStatus } from './plans/stateMachine.js';
import type {
  PlanRow,
  PlanActionRow,
  PlanEventRow,
  CreatePlanInput,
  RecordClickResult,
  TransitionInput,
  PlanKind,
  PlanSeverity,
  PlanSource,
  ActorSource,
} from './plans/types.js';

// ─── ID generator ────────────────────────────────────────────────────
// pl_ + 12 hex chars. ~16M values per prefix; uniqueness via DB PK.

function generatePlanId(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(6));
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
  return `pl_${hex}`;
}

// ─── Create ─────────────────────────────────────────────────────────

export async function createPlan(input: CreatePlanInput): Promise<PlanRow> {
  const planId = input.id ?? generatePlanId();
  const expiresAt = input.expiresAt ?? defaultExpiresAt();

  return db.transaction(async (client) => {
    const planResult = await client.query<PlanRow>(
      `INSERT INTO plans (
         id, kind, status, severity, source, source_metadata,
         target, summary, proposed_fix, expires_at
       )
       VALUES ($1, $2, 'pending', $3, $4, $5::jsonb, $6, $7, $8::jsonb, $9)
       RETURNING *`,
      [
        planId,
        input.kind,
        input.severity ?? 'info',
        input.source,
        JSON.stringify(input.sourceMetadata ?? {}),
        input.target ?? null,
        input.summary,
        input.proposedFix ? JSON.stringify(input.proposedFix) : null,
        expiresAt,
      ],
    );
    const plan = planResult.rows[0];

    // Insert plan_actions in display order
    for (let i = 0; i < input.actions.length; i++) {
      const a = input.actions[i];
      await client.query(
        `INSERT INTO plan_actions (plan_id, action_id, label, style, ordering, click_payload)
         VALUES ($1, $2, $3, $4, $5, $6::jsonb)`,
        [
          planId,
          a.actionId,
          a.label,
          a.style ?? 'secondary',
          i,
          JSON.stringify(a.clickPayload ?? {}),
        ],
      );
    }

    // Emit created event
    await client.query(
      `INSERT INTO plan_events (plan_id, event_type, actor_source, detail)
       VALUES ($1, 'created', 'system', $2::jsonb)`,
      [planId, JSON.stringify({ kind: input.kind, source: input.source })],
    );

    logger.info('Plan created', {
      planId,
      kind: input.kind,
      severity: input.severity ?? 'info',
      source: input.source,
      actionCount: input.actions.length,
    });

    return plan;
  });
}

// ─── Mark presented ──────────────────────────────────────────────────
// Notification router calls this once the Discord post / MC bell event
// has been dispatched. Transitions pending → presented.

export async function presentPlan(planId: string): Promise<PlanRow | null> {
  return db.transaction(async (client) => {
    const cur = await fetchPlanForUpdate(client, planId);
    if (!cur) return null;
    if (!isValidTransition(cur.status as PlanStatus, 'presented')) {
      logger.warn('presentPlan: invalid transition', { planId, from: cur.status });
      return cur;
    }
    const upd = await client.query<PlanRow>(
      `UPDATE plans SET status = 'presented' WHERE id = $1 RETURNING *`,
      [planId],
    );
    await client.query(
      `INSERT INTO plan_events (plan_id, event_type, actor_source, from_status, to_status)
       VALUES ($1, 'presented', 'system', $2, 'presented')`,
      [planId, cur.status],
    );
    return upd.rows[0];
  });
}

// ─── Record a click — atomic first-click-wins idempotency ──────────────
// Returns:
//   { ok: true, action } — first click; act on this
//   { ok: false, reason: 'duplicate', currentStatus } — already acted on
//   { ok: false, reason: 'plan_not_found' | 'action_not_found' | 'plan_closed' }

export async function recordClick(args: {
  planId: string;
  actionId: string;
  actorUserId: string;
  actorSource: ActorSource;
}): Promise<RecordClickResult> {
  const { planId, actionId, actorUserId, actorSource } = args;

  return db.transaction(async (client) => {
    const plan = await fetchPlanForUpdate(client, planId);
    if (!plan) return { ok: false, reason: 'plan_not_found' };
    if (plan.closed_at !== null) {
      return { ok: false, reason: 'plan_closed', currentStatus: plan.status as PlanStatus };
    }

    // Atomic claim: only succeeds if acted_at IS NULL
    const claim = await client.query<PlanActionRow>(
      `UPDATE plan_actions
         SET acted_at = NOW(), acted_by_user = $3
       WHERE plan_id = $1 AND action_id = $2 AND acted_at IS NULL
       RETURNING *`,
      [planId, actionId, actorUserId],
    );

    if (claim.rowCount === 0) {
      // Either the action doesn't exist or it was already clicked
      const existing = await client.query<PlanActionRow>(
        `SELECT * FROM plan_actions WHERE plan_id = $1 AND action_id = $2`,
        [planId, actionId],
      );
      if (existing.rowCount === 0) {
        return { ok: false, reason: 'action_not_found' };
      }
      // Already clicked — log duplicate_click event for audit
      await client.query(
        `INSERT INTO plan_events (plan_id, event_type, action_id, actor_user_id, actor_source, detail)
         VALUES ($1, 'duplicate_click', $2, $3, $4, $5::jsonb)`,
        [
          planId,
          actionId,
          actorUserId,
          actorSource,
          JSON.stringify({ previouslyActedBy: existing.rows[0].acted_by_user, previouslyActedAt: existing.rows[0].acted_at }),
        ],
      );
      return {
        ok: false,
        reason: 'duplicate',
        currentStatus: plan.status as PlanStatus,
        previouslyActedBy: existing.rows[0].acted_by_user,
        previouslyActedAt: existing.rows[0].acted_at,
      };
    }

    // First click wins — log clicked event + transition pending/presented → clicked
    await client.query(
      `INSERT INTO plan_events (plan_id, event_type, action_id, actor_user_id, actor_source, detail)
       VALUES ($1, 'clicked', $2, $3, $4, $5::jsonb)`,
      [planId, actionId, actorUserId, actorSource, JSON.stringify({ label: claim.rows[0].label })],
    );

    if (isValidTransition(plan.status as PlanStatus, 'clicked')) {
      await client.query(
        `UPDATE plans
           SET status = 'clicked',
               approved_by_mc_user_id = $2,
               approved_via = $3
         WHERE id = $1`,
        [planId, actorUserId, actorSource === 'agent' || actorSource === 'system' ? 'api' : actorSource],
      );
      await client.query(
        `INSERT INTO plan_events (plan_id, event_type, actor_source, from_status, to_status)
         VALUES ($1, 'state_change', 'system', $2, 'clicked')`,
        [planId, plan.status],
      );
    }

    logger.info('Plan action clicked', { planId, actionId, actorUserId, actorSource });

    return { ok: true, action: claim.rows[0] };
  });
}

// ─── Dispatch — link agent_run created from this plan ──────────────────

export async function dispatchPlan(args: {
  planId: string;
  agentRunId: string; // UUID
}): Promise<PlanRow | null> {
  const { planId, agentRunId } = args;

  return db.transaction(async (client) => {
    const cur = await fetchPlanForUpdate(client, planId);
    if (!cur) return null;
    if (!isValidTransition(cur.status as PlanStatus, 'dispatched')) {
      logger.warn('dispatchPlan: invalid transition', { planId, from: cur.status });
      return cur;
    }

    const upd = await client.query<PlanRow>(
      `UPDATE plans
         SET status = 'dispatched',
             triggered_agent_run_id = $2
       WHERE id = $1
       RETURNING *`,
      [planId, agentRunId],
    );

    await client.query(
      `INSERT INTO plan_events (plan_id, event_type, actor_source, from_status, to_status, detail)
       VALUES ($1, 'dispatched', 'system', $2, 'dispatched', $3::jsonb)`,
      [planId, cur.status, JSON.stringify({ agentRunId })],
    );

    return upd.rows[0];
  });
}

// ─── General state transition ────────────────────────────────────────
// Used for in_progress / succeeded / failed / stuck / resolved / expired
// / dismissed transitions. Caller provides the target status + optional
// payload fields (result, error_summary, proposals).

export async function transitionStatus(input: TransitionInput): Promise<PlanRow | null> {
  const { planId, toStatus, actorUserId, actorSource, payload } = input;

  return db.transaction(async (client) => {
    const cur = await fetchPlanForUpdate(client, planId);
    if (!cur) return null;
    if (!isValidTransition(cur.status as PlanStatus, toStatus)) {
      logger.warn('transitionStatus: invalid transition', {
        planId,
        from: cur.status,
        to: toStatus,
      });
      return cur;
    }

    const closesPlan = ['succeeded', 'failed', 'resolved', 'dismissed', 'expired'].includes(toStatus);

    const upd = await client.query<PlanRow>(
      `UPDATE plans
         SET status = $2,
             result = COALESCE($3::jsonb, result),
             error_summary = COALESCE($4, error_summary),
             proposals = COALESCE($5::jsonb, proposals),
             closed_at = CASE WHEN $6::boolean THEN NOW() ELSE closed_at END
       WHERE id = $1
       RETURNING *`,
      [
        planId,
        toStatus,
        payload?.result ? JSON.stringify(payload.result) : null,
        payload?.errorSummary ?? null,
        payload?.proposals ? JSON.stringify(payload.proposals) : null,
        closesPlan,
      ],
    );

    // Map terminal state to its specific event_type for richer timelines
    const eventType =
      toStatus === 'succeeded' || toStatus === 'failed' || toStatus === 'stuck' ||
      toStatus === 'dismissed' || toStatus === 'expired' || toStatus === 'resolved'
        ? toStatus
        : 'state_change';

    await client.query(
      `INSERT INTO plan_events (plan_id, event_type, actor_user_id, actor_source, from_status, to_status, detail)
       VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb)`,
      [
        planId,
        eventType,
        actorUserId ?? null,
        actorSource,
        cur.status,
        toStatus,
        JSON.stringify(payload ?? {}),
      ],
    );

    logger.info('Plan transitioned', { planId, from: cur.status, to: toStatus, actorSource });

    return upd.rows[0];
  });
}

// ─── Queries ─────────────────────────────────────────────────────────

export async function getPlan(planId: string): Promise<PlanRow | null> {
  return db.queryOne<PlanRow>(`SELECT * FROM plans WHERE id = $1`, [planId]);
}

export async function getPlanActions(planId: string): Promise<PlanActionRow[]> {
  return db.queryMany<PlanActionRow>(
    `SELECT * FROM plan_actions WHERE plan_id = $1 ORDER BY ordering ASC`,
    [planId],
  );
}

export async function getPlanEvents(planId: string, limit = 200): Promise<PlanEventRow[]> {
  return db.queryMany<PlanEventRow>(
    `SELECT * FROM plan_events
     WHERE plan_id = $1
     ORDER BY occurred_at ASC, id ASC
     LIMIT $2`,
    [planId, limit],
  );
}

export interface ListPlansOpts {
  status?: PlanStatus | PlanStatus[];
  kind?: PlanKind | PlanKind[];
  source?: PlanSource;
  active?: boolean;          // shortcut: status IN (pending,presented,clicked,dispatched,in_progress,stuck)
  limit?: number;
  offset?: number;
}

export async function listPlans(opts: ListPlansOpts = {}): Promise<PlanRow[]> {
  const conditions: string[] = [];
  const params: Array<string | number | string[]> = [];

  if (opts.active) {
    conditions.push(`status IN ('pending','presented','clicked','dispatched','in_progress','stuck')`);
  } else if (opts.status) {
    const arr = Array.isArray(opts.status) ? opts.status : [opts.status];
    params.push(arr);
    conditions.push(`status = ANY($${params.length}::text[])`);
  }
  if (opts.kind) {
    const arr = Array.isArray(opts.kind) ? opts.kind : [opts.kind];
    params.push(arr);
    conditions.push(`kind = ANY($${params.length}::text[])`);
  }
  if (opts.source) {
    params.push(opts.source);
    conditions.push(`source = $${params.length}`);
  }

  const limit = opts.limit ?? 100;
  const offset = opts.offset ?? 0;
  params.push(limit, offset);

  const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
  const sql = `SELECT * FROM plans ${where}
               ORDER BY created_at DESC
               LIMIT $${params.length - 1} OFFSET $${params.length}`;

  return db.queryMany<PlanRow>(sql, params);
}

/** For PB.8 expiry sweep: plans presented past their expires_at, not yet closed. */
export async function listExpiredPresented(limit = 50): Promise<PlanRow[]> {
  return db.queryMany<PlanRow>(
    `SELECT * FROM plans
     WHERE status = 'presented'
       AND expires_at IS NOT NULL
       AND expires_at < NOW()
     ORDER BY expires_at ASC
     LIMIT $1`,
    [limit],
  );
}

// ─── Manual event logger (for agent progress, comments, etc.) ──────────

export async function logEvent(args: {
  planId: string;
  eventType: 'agent_progress' | 'comment';
  actorUserId?: string | null;
  actorSource: ActorSource;
  detail: Record<string, unknown>;
}): Promise<PlanEventRow> {
  const row = await db.queryOne<PlanEventRow>(
    `INSERT INTO plan_events (plan_id, event_type, actor_user_id, actor_source, detail)
     VALUES ($1, $2, $3, $4, $5::jsonb)
     RETURNING *`,
    [args.planId, args.eventType, args.actorUserId ?? null, args.actorSource, JSON.stringify(args.detail)],
  );
  if (!row) throw new Error('logEvent: insert returned no row');
  return row;
}

// ─── Helpers ─────────────────────────────────────────────────────────

async function fetchPlanForUpdate(
  client: { query: <T>(sql: string, params?: unknown[]) => Promise<{ rows: T[]; rowCount: number }> },
  planId: string,
): Promise<PlanRow | null> {
  const result = await client.query<PlanRow>(
    `SELECT * FROM plans WHERE id = $1 FOR UPDATE`,
    [planId],
  );
  return result.rows[0] ?? null;
}

function defaultExpiresAt(): Date {
  // 24h default; PB.5 settings will override at create time once it lands.
  return new Date(Date.now() + 24 * 60 * 60 * 1000);
}

// Re-export types so callers can import everything from one place
export type {
  PlanRow,
  PlanActionRow,
  PlanEventRow,
  CreatePlanInput,
  RecordClickResult,
  TransitionInput,
  PlanKind,
  PlanSeverity,
  PlanSource,
  ActorSource,
};
export type { PlanStatus } from './plans/stateMachine.js';
